# Generated by Django 2.2 on 2021-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo de la norma')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Identificacion de la norma')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de publicacion')),
                ('texto', models.FileField(upload_to='normativas')),
            ],
            options={
                'verbose_name': 'Normativa',
                'verbose_name_plural': 'Normativas',
                'ordering': ['titulo'],
            },
        ),
    ]
