# Generated by Django 2.2 on 2021-03-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0002_auto_20210330_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaOperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del documento')),
                ('tipo', models.CharField(choices=[('OS', 'Orden de Servicio'), ('CIR', 'Circular'), ('MEMO', 'Memorandun')], max_length=4, verbose_name='Tipo de norma')),
                ('numero', models.DateField(verbose_name='Numero del documento')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo de documento')),
                ('texto', models.FileField(upload_to='normaOperativa')),
            ],
            options={
                'verbose_name': 'Norma operativa',
                'verbose_name_plural': 'Normas operativas',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='RequisitosExpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais a exportar')),
                ('fecha', models.DateField(verbose_name='Fecha del documento')),
                ('identificacion', models.DateField(verbose_name='Fecha del documento')),
                ('texto', models.FileField(upload_to='reqExpo')),
            ],
            options={
                'verbose_name': 'Requisito/exportacion',
                'verbose_name_plural': 'Requisitos/exportacion',
                'ordering': ['fecha'],
            },
        ),
    ]
