# Generated by Django 2.2 on 2021-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0003_normaoperativa_requisitosexpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaoperativa',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Numero del documento'),
        ),
    ]
