# Generated by Django 2.2 on 2021-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0004_auto_20210330_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaoperativa',
            name='tema',
            field=models.CharField(default=1, max_length=50, verbose_name='Tema'),
            preserve_default=False,
        ),
    ]
