# Generated by Django 2.2 on 2021-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0006_tematicadocumental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tematicadocumental',
            name='texto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
