# Generated by Django 2.2 on 2021-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0007_auto_20210401_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LACT', 'Lacteos'), ('MIEL', 'Miel')], max_length=5, verbose_name='Tipo de alimento')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nombre'],
            },
        ),
    ]
