# Generated by Django 2.2 on 2021-04-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0008_alimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='caa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Articulo del CAA'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
