# Generated by Django 2.2 on 2021-04-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0010_auto_20210403_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='tipo',
            field=models.CharField(choices=[('Lacteos', 'Lacteos'), ('Miel', 'Miel')], max_length=6, verbose_name='Tipo de alimento'),
        ),
    ]
