# Generated by Django 2.2 on 2021-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0011_auto_20210403_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='tipo',
            field=models.CharField(choices=[('Lacteos', 'Lacteos'), ('Miel', 'Miel')], max_length=8, verbose_name='Tipo de alimento'),
        ),
    ]
