# Generated by Django 2.2 on 2021-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0013_auto_20210404_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='temasNormas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
            ],
        ),
    ]
