# Generated by Django 2.2 on 2021-04-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0015_auto_20210405_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentacion.temasNormas'),
        ),
    ]
