# Generated by Django 2.2 on 2021-04-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0016_auto_20210405_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del documento'),
        ),
    ]
