# Generated by Django 2.2 on 2021-04-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0017_auto_20210405_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='norma',
            field=models.FileField(blank=True, null=True, upload_to='normas_Alimentos'),
        ),
    ]
