# Generated by Django 2.2 on 2021-04-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0018_alimento_norma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativa',
            name='tipo',
            field=models.CharField(choices=[('CIRCULAR', 'Circular'), ('CAA', 'Codigo Alimentario Argentino'), ('MEMORANDUN', 'Memorandun'), ('ORDEN SERVICIO', 'Orden de Servicio'), ('R80', 'Resol 80/96 - GMC')], max_length=10, verbose_name='Tipo de norma'),
        ),
    ]
