# Generated by Django 2.2 on 2021-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0019_auto_20210409_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodAliArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(max_length=4, unique=True, verbose_name='Capitulo')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('texto', models.FileField(upload_to='CAA', verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Codigo Alimentario Argentino',
                'verbose_name_plural': 'Codigo Alimentario Argentino',
            },
        ),
    ]
