# Generated by Django 2.2 on 2021-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0020_codaliarg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codaliarg',
            name='cap',
            field=models.CharField(max_length=15, unique=True, verbose_name='Capitulo'),
        ),
    ]
