# Generated by Django 2.2 on 2021-04-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0021_auto_20210410_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifi', models.CharField(max_length=100, unique=True, verbose_name='Identificacion de la norma')),
                ('texto', models.FileField(upload_to='Codex', verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Codex Alimentarius',
                'verbose_name_plural': 'Codex Alimentarius',
            },
        ),
    ]
