# Generated by Django 2.2 on 2021-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre producto')),
                ('codigo', models.CharField(max_length=100, verbose_name='Nombre producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['tipo'],
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numero'),
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='productos',
        ),
        migrations.AddField(
            model_name='empresa',
            name='productos',
            field=models.ManyToManyField(to='empresas.Productos'),
        ),
    ]
