# Generated by Django 2.2 on 2021-04-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20210419_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTecnologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, unique=True, verbose_name='Grupo/Subgrupo')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Grupo/Subgrupo')),
            ],
            options={
                'verbose_name': 'Grupo Tecnologico',
                'verbose_name_plural': 'Grupos Tecnologicos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo de la auditoria')),
                ('criterio', models.CharField(max_length=250, verbose_name='Criterios de auditoria')),
                ('alcance', models.CharField(max_length=250, verbose_name='Alcance de auditoria')),
                ('evidencia', models.TextField(verbose_name='Evidencias encontradas')),
                ('nc', models.TextField(verbose_name='No conformidades/Conclusiones')),
                ('estado', models.BooleanField(default=False, verbose_name='Abierta/Cerrada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='grupos_id',
            field=models.ManyToManyField(to='empresas.GrupoTecnologico'),
        ),
    ]
