# Generated by Django 2.2 on 2021-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_auto_20210419_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Pais exportador')),
            ],
            options={
                'verbose_name': 'Pais exportador',
                'verbose_name_plural': 'Paises exportadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='empresa',
            name='grupos_id',
            field=models.ManyToManyField(to='empresas.GrupoTecnologico', verbose_name='Grupos tecnologicos'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='productos_id',
            field=models.ManyToManyField(to='empresas.Producto', verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='paises_id',
            field=models.ManyToManyField(to='empresas.Pais', verbose_name='Paises habilitados'),
        ),
    ]
