# Generated by Django 2.2 on 2021-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20210420_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupotecnologico',
            name='descripcion',
            field=models.CharField(max_length=200, unique=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='grupotecnologico',
            name='numero',
            field=models.CharField(max_length=5, unique=True, verbose_name='Numero Grupo'),
        ),
    ]
