# Generated by Django 2.2 on 2021-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_auto_20210422_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='jefe_planta',
            field=models.CharField(default=1, max_length=100, verbose_name='Jefe de Planta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='jefe_servicio_sanitario',
            field=models.CharField(default=1, max_length=100, verbose_name='Jefe de Servicio Oficial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='lineas_haccp',
            field=models.CharField(default=1, max_length=300, verbose_name='Jefe de Servicio Oficial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='resp_inocuidad',
            field=models.CharField(default=1, max_length=100, verbose_name='Responsable de inocuidad'),
            preserve_default=False,
        ),
    ]
