# Generated by Django 2.2 on 2021-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_auto_20210422_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='auditados',
            field=models.CharField(default=1, max_length=250, verbose_name='Personas de empresa auditada:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditoria',
            name='auditores',
            field=models.CharField(default=1, max_length=250, verbose_name='Auditor/Auditores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditoria',
            name='observaciones',
            field=models.TextField(default=1, verbose_name='Aclaraciones/Conclusiones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='nc',
            field=models.TextField(verbose_name='No conformidades'),
        ),
    ]
