# Generated by Django 2.2 on 2021-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_auto_20210426_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='grupos_id',
            field=models.ManyToManyField(to='empresas.GrupoTecnologico', verbose_name='Grupos tecnologicos habilitados'),
        ),
    ]
