# Generated by Django 2.2 on 2021-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
