# Generated by Django 2.2 on 2021-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_auto_20210430_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='agua',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
