# Generated by Django 2.2 on 2021-04-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_agua_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agua',
            name='resultado',
            field=models.BooleanField(verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='agua',
            name='tipo_agua',
            field=models.CharField(choices=[('Agua Osmosis', 'Agua Osmosis'), ('Agua de pozo', 'Agua de pozo'), ('Agua de red', 'Agua de red')], max_length=12, verbose_name='Fuente de agua '),
        ),
    ]
