# Generated by Django 2.2 on 2021-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_auto_20210430_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='agua',
            name='acta',
            field=models.CharField(default=1, max_length=10, verbose_name='Numero de acta'),
            preserve_default=False,
        ),
    ]
